const channels = [
  "TFC",
  "GMA Life TV",
  "GMA News",
  "GMA Pinoy",
  "WAPA America HD",
  "Willow HD",
  "NBC San Diego HD",
  "CBS San Diego HD",
  "Velocity HD",
  "MSNBC HD",
  "MTV HD",
  "FreeForm HD",
  "OWN HD",
  "ABC San Diego HD",
  "FOX San Diego HD",
  "TVO HD",
  "BBC America HD",
  "Sky Sports Main Event HD",
  "Sky Sports Main Event",
  "Sky Sports Cricket HD",
  "Sky Sports Cricket",
  "Sky Sports Action HD",
  "Sky Sports Action",
  "Sky Sports Golf HD",
  "Sky Sports Golf",
  "Sky Sports Premier League HD",
  "Sky Sports Premier League",
  "Sky Sports F1 HD",
  "Sky Sports F1",
  "Sky Sports Arena HD",
  "Sky Sports Arena",
  "Sky Sports Football HD",
  "Sky Sports Football",
  "Sky Sports Mix HD",
  "Sky Sports Mix",
  "Sky Sports News HD",
  "Sky Sports News",
  "BT Sports 1 HD",
  "BT Sports 1",
  "BT Sports 2 HD",
  "BT Sports 2",
  "BT Sports 3 HD",
  "BT Sports 3",
  "BT Sports ESPN HD",
  "BT Sports ESPN",
  "Eurosport 1 HD",
  "Eurosport 2 HD",
  "Chelsea TV HD",
  "MUTV HD",
  "LFC TV HD",
  "Premier Sports HD",
  "Racing UK HD",
  "Motors TV UK",
  "At The Races",
  "Eir Sports 1 HD",
  "Boxnation",
  "Golf Channel HD",
  "NBC Sports Network HD",
  "CBS Sports Network HD",
  "BeIN Sports USA HD",
  "BeIN Sports Espanol HD",
  "BeIN Sports 11 HD",
  "BeIN Sports 12 HD",
  "Fox Sports 1 HD",
  "Fox Sports 2 HD",
  "Fox Soccer Plus HD",
  "Fox Deportes HD",
  "Fox Sports Arizona HD",
  "Fox Sports Carolina HD",
  "Fox Sports Cincinnati HD",
  "Fox Sports Detroit HD",
  "Fox Sports Florida HD",
  "Fox Sports Indiana HD",
  "Fox Sports North HD",
  "Fox Sports Ohio HD",
  "Fox Sports San Diego HD",
  "Fox Sports South East HD",
  "Fox Sports South Georgia HD",
  "Fox Sports South HD",
  "Fox Sports Sun HD",
  "Fox Sports Tennessee HD",
  "Fox Sports West HD",
  "Fox Sports Wisconsin HD",
  "CSN Philly HD",
  "CSN California HD",
  "CSN Chicago HD",
  "CSN Northwest HD",
  "CSN Bay Area HD",
  "CSN Mid Atlantic HD",
  "CSN New England HD",
  "NESN HD",
  "NESN Plus HD",
  "ESPN HD",
  "ESPN 2 HD",
  "ESPN U HD",
  "ESPNews HD",
  "ESPN Deportes HD",
  "MLB Network HD",
  "NBA TV HD",
  "NFL Network HD",
  "NHL Network HD",
  "YES Network HD",
  "WWE Network HD",
  "SEC Network HD",
  "Big Ten Network HD",
  "Longhorn Network HD",
  "Tennis Channel HD",
  "PAC 12 Network HD",
  "PAC 12 Washington HD",
  "PAC 12 Oregon HD",
  "PAC 12 Los Angeles HD",
  "PAC 12 Mountain HD",
  "PAC 12 Arizona HD",
  "PAC 12 Bay Area HD",
  "Sportsnet 360 HD",
  "Sportsnet East HD",
  "Sportsnet One HD",
  "Sportsnet Ontario HD",
  "Sportsnet Pacific HD",
  "Sportsnet West HD",
  "Sportsnet World HD",
  "TSN 1 HD",
  "TSN 2 HD",
  "TSN 3 HD",
  "TSN 4 HD",
  "TSN 5 HD",
  "RDS HD",
  "Univision Deportes HD",
  "Gol TV HD",
  "UFC TV HD",
  "OSN Cricket HD",
  "Ten Sports",
  "PTV Sports",
  "Sony Six",
  "Neo Prime",
  "Rai 1 HD",
  "Rai 2 HD",
  "Rai 3 HD",
  "Rai 4 HD",
  "Rai News 24 HD",
  "Rai Premium HD",
  "Rai Storia HD",
  "Rai Scuola HD",
  "Rai YoYo HD",
  "Rai Gulp HD",
  "Rai Movies HD",
  "Roma",
  "Canale 5 Mediaset HD",
  "INTER Channel",
  "Itaila 1 Mediaset HD",
  "Rete 4 Mediaset HD",
  "RSI La1 HD",
  "RSI La2 HD",
  "Fox IT HD",
  "Nat Geo IT HD",
  "Nat Geo Wild IT HD",
  "Discovery Science IT HD",
  "Discovery Channel IT HD",
  "Disney Channel IT HD",
  "Sky TG 24",
  "Sky Uno HD",
  "Sky Atlantic IT HD",
  "Sky Arte IT HD",
  "Sky Cinema Classics HD",
  "Sky Cinema Comedy IT HD",
  "Sky Cinema Hits IT HD",
  "Sky Cinema Max HD",
  "Sky Cinema Passion HD",
  "Sky Cinema Uno IT HD",
  "Premium Cinema HD",
  "Premium Cinema 2 HD",
  "Premium Cinema Action HD",
  "Premium Cinema Energy HD",
  "Sky Sport 24 HD",
  "Sky Sport 1 IT HD",
  "Sky Sport 2 IT HD",
  "Sky Sport 3 IT HD",
  "Sky Sport F1 IT HD",
  "Sky Sport GP IT HD",
  "Sky Sport Plus IT HD",
  "Sky Fox Sport HD",
  "Sky Supercalcio HD",
  "Rai Sport + HD",
  "Super Tennis HD",
  "Univision HD",
  "Univision Miami HD",
  "Unimas HD",
  "Telemundo HD",
  "Telemundo Los Angeles HD",
  "NBC Universo HD",
  "NBC Universo 2 HD",
  "Galavision HD",
  "Azteca 7",
  "Azteca 13",
  "26 TV HD",
  "A&E LT HD",
  "AMC LT HD",
  "AXN LT HD",
  "Animal Planet HD LT",
  "Bandamax LT",
  "Boomerang LT",
  "Cartoon Network LT",
  "Canal 11",
  "Canal 5 HD",
  "Canal De Las Estrellas",
  "Cinecanal",
  "Cinemax LT",
  "CNN LT",
  "Comedy Central LT",
  "Discovery Channel LT HD",
  "Discovery Civilization",
  "Discovery Kids",
  "Discovery Home & Health",
  "Discovery Science LT",
  "Discovery Theater",
  "Discovery Turbo LT",
  "Disney LT HD",
  "Disney Jr LT",
  "Disney XD LT",
  "De Pelicula",
  "E! LT",
  "ESPN LT",
  "ESPN 2 LT",
  "ESPN 3 LT",
  "Fox Action LT",
  "Fox Cinema LT",
  "Fox Movies LT",
  "Fox Sports LT HD",
  "Fox Sports 2 LT HD",
  "Fox Sports 3 LT HD",
  "HBO LT HD",
  "HBO Plus LT HD",
  "HBO Family LT HD",
  "HBO Signature LT HD",
  "History LT HD",
  "MTV Latino",
  "Nat Geo LT",
  "Nat Geo Wild LT",
  "Nickelodeon LT",
  "Nick Jr LT",
  "Sony LT",
  "TNT LT",
  "MiMusica HD",
  "La 1 HD",
  "Antena 3 HD",
  "Cuatro HD",
  "Telecinco HD",
  "La Sexta HD",
  "Neox HD",
  "A3Series HD",
  "Mega HD",
  "#0 HD",
  "Movistar+ Series HD",
  "Movistar+ Accion HD",
  "Movistar+ Comedia HD",
  "Movistar+ DCine HD",
  "Movistar+ Xtra HD",
  "AMC ES HD",
  "TCM ES HD",
  "AXN HD",
  "AXN White HD",
  "Calle 13 HD",
  "Hollywood HD",
  "Cosmo HD",
  "Fox ES HD",
  "Fox Life ES HD",
  "TNT ES HD",
  "SyFy ES HD",
  "Comedy Central ES HD",
  "Discovery Channel ES HD",
  "Caza y Pesca HD",
  "Historia HD",
  "Viajar HD",
  "National Geographic ES HD",
  "National Geographic Wild ES HD",
  "Disney Channel ES HD",
  "Nickelodeon ES HD",
  "Mezzo Live HD",
  "Movistar+ Deportes 1 HD",
  "Movistar+ Deportes 2 HD",
  "Movistar+ F1 HD",
  "Movistar+ Futbol HD",
  "Movistar+ Golf HD",
  "Movistar+ MotoGP HD",
  "BeIN Sports Espana HD",
  "BeIN Sports LaLiga HD",
  "LaLigaTV HD",
  "Toros TV HD",
  "Das Erste HD",
  "ZDF HD",
  "3Sat HD",
  "RTL HD",
  "RTL 2 HD",
  "Super RTL HD",
  "Sat.1 HD",
  "Kabel Eins HD",
  "Pro Sieben HD",
  "DMAX HD",
  "Pro Sieben Maxx HD",
  "RTL Crime HD",
  "RTL Nitro HD",
  "Sat1 Gold HD",
  "Vox HD",
  "Sixx HD",
  "Tele 5 HD",
  "ORF 1 HD",
  "ORF 2 HD",
  "N-TV HD",
  "N24 HD",
  "TLC DE HD",
  "Sky 1 DE HD",
  "Sky Atlantic DE HD",
  "Sky Arts DE HD",
  "Sky Cinema DE HD",
  "Sky Action DE HD",
  "Travel Channel DE HD",
  "History DE HD",
  "Nat Geo DE HD",
  "Nat Geo Wild DE HD",
  "Nickelodeon DE HD",
  "Discovery Channel DE HD",
  "Disney Channel DE HD",
  "Disney Junior DE HD",
  "Sky Sport Austria HD",
  "Sky Sport News HD",
  "Sportdigital HD",
  "Sky Bundesliga 1 HD",
  "Sky Bundesliga 2 DE HD",
  "Sky Bundesliga 3 DE HD",
  "Sky Bundesliga 4 DE HD",
  "Sky Bundesliga DE 5",
  "Sky Bundesliga DE 6",
  "Sky Bundesliga DE 7",
  "Sky Bundesliga DE 8",
  "Sky Bundesliga DE 9",
  "Sky Bundesliga DE 10",
  "Sky Sport 1 DE HD",
  "Sky Sport 2 DE HD",
  "Sky Sport DE 3 HD",
  "Sky Sport DE 4 HD",
  "Sky Sport DE 5 HD",
  "Sky Sport DE 6",
  "Sky Sport DE 7",
  "Sky Sport DE 8",
  "Sky Sport DE 9",
  "Sky Sport DE 10",
  "Sky Sports News DE HD",
  "RTP 1",
  "RTP 2",
  "RTP Acores",
  "RTP Africa",
  "RTP Madeira",
  "RTP Memoria",
  "Sic",
  "Sic Mulher HD",
  "Sic Noticias HD",
  "Sic Radical HD",
  "TV Cine 1 HD",
  "TV Cine 2 HD",
  "TV Cine 3 HD",
  "TV Cine 4 HD",
  "TVI",
  "TVI 24",
  "TVI Reality",
  "TV Globo",
  "Sport TV + HD",
  "Sport TV 1 HD",
  "Sport TV 2 HD",
  "Sport TV 3 HD",
  "Sport TV 4 HD",
  "Sport TV 5 HD",
  "Benfica TV HD",
  "RTE One",
  "RTE Two",
  "RTE Jr",
  "TG4",
  "TV3",
  "UTV HD",
  "3e",
  "BBC One HD",
  "BBC One",
  "BBC Two HD",
  "BBC Two",
  "BBC Four HD",
  "BBC Four",
  "BBC News HD",
  "BBC News",
  "Channel 4 HD",
  "Channel 4",
  "Channel 5 HD",
  "Channel 5",
  "ITV 1 HD",
  "ITV 1",
  "ITV 2 HD",
  "ITV 2",
  "ITV 3 HD",
  "ITV 3",
  "ITV 4 HD",
  "ITV 4",
  "ITV Encore HD",
  "ITV Encore",
  "Sky 1",
  "Sky 2",
  "Sky Arts",
  "Sky Atlantic",
  "Sky Living",
  "Sky News HD",
  "E4",
  "More4",
  "Pick TV",
  "5USA",
  "5STAR",
  "CBS Drama",
  "CBS Reality",
  "CBS Action",
  "Comedy Central UK",
  "Comedy Central Extra",
  "Dave",
  "Home",
  "Gold",
  "Eden HD",
  "Universal Channel",
  "Syfy UK",
  "Lifetime UK",
  "Yesterday",
  "Drama",
  "Watch",
  "Really",
  "Food Network UK",
  "Good Food",
  "Challenge",
  "Alibi",
  "TLC UK",
  "ID UK",
  "Crime + Investigation UK",
  "Discovery Channel UK",
  "Discovery Science UK",
  "Discovery Turbo",
  "Discovery History",
  "Animal Planet UK",
  "National Geographic UK",
  "Nat Geo Wild UK",
  "Boomerang UK",
  "Cartoon Network UK",
  "Cartoonito UK",
  "Nickelodeon UK",
  "Nick Jr UK",
  "Nick Jr Too UK",
  "Nicktoons UK",
  "CBBC HD",
  "CBeebies",
  "Disney Channel UK",
  "Disney Junior UK",
  "Disney XD UK",
  "BabyTV",
  "Pop UK",
  "Tiny Pop UK",
  "Pop Max UK",
  "H2",
  "E! UK",
  "MTV UK",
  "Fox UK",
  "Sky 1 HD",
  "Sky Cinema Drama HD",
  "Sky Cinema Comedy HD",
  "Sky Cinema Villians HD",
  "Sky Cinema Premiere HD",
  "Sky Cinema Sci-Fi & Horror HD",
  "Sky Cinema Thriller HD",
  "Global BC",
  "CBC Vancover",
  "CTV 2 Vancover Island",
  "CTV Vancouver",
  "CityTV Vancouver",
  "CTV Montreal HD",
  "CBC Montreal HD",
  "CityTV Montreal HD",
  "Global HD",
  "CBC HD",
  "CTV HD",
  "CityTV HD",
  "OMNI 1 HD",
  "OMNI 2 HD",
  "CP24 HD",
  "CHCH HD",
  "CTV News HD",
  "CBC News HD",
  "BNN HD",
  "Animal Planet CA HD",
  "Nat Geo CA HD",
  "Nat Geo Wild CA HD",
  "Love Nature HD",
  "BBC Earth HD",
  "LCN HD",
  "W Network HD",
  "Space HD",
  "Slice HD",
  "Peachtree HD",
  "ID HD",
  "HGTV CA HD",
  "TLC CA HD",
  "Bravo CA HD",
  "OWN CA HD",
  "Discovery Channel CA HD",
  "Velocity CA HD",
  "DTour HD",
  "E! HD",
  "Gusto HD",
  "Much Music HD",
  "Vision TV HD",
  "Smithsonian Channel HD",
  "ABC Spark HD",
  "Disney Channel CA HD",
  "Disney Jr CA HD",
  "Family CHRGD HD",
  "Family HD",
  "Treehouse HD",
  "Teletoon HD",
  "YTV HD",
  "ABC HD",
  "CBS HD",
  "NBC HD",
  "FOX HD",
  "CW HD",
  "A&E HD",
  "AMC HD",
  "Food Network HD",
  "Cooking Channel HD",
  "Animal Planet HD",
  "Bravo HD",
  "Cartoon Network HD",
  "Fox Business HD",
  "CNBC HD",
  "CNN News HD",
  "Comedy Central HD",
  "Destination America HD",
  "Discovery Channel HD",
  "Discovery Family HD",
  "Discovery Science HD",
  "Discovery Life HD",
  "Nat Geo HD",
  "Nat Geo Wild HD",
  "History HD",
  "Fox News HD",
  "Weather Network HD",
  "FX HD",
  "FXX HD",
  "FXM HD",
  "El Rey Network HD",
  "Nick HD",
  "Nick Jr HD",
  "Disney Channel HD",
  "Disney Jr HD",
  "Disney XD HD",
  "Universal Kids HD",
  "Lifetime HD",
  "Spike HD",
  "TBS HD",
  "TNT HD",
  "USA Network HD",
  "Travel Channel HD",
  "Outdoor Channel HD",
  "Oxygen HD",
  "SYFY HD",
  "Sundance HD",
  "HGTV HD",
  "DIY Network HD",
  "American Heroes Channel HD",
  "Hallmark Channel HD",
  "Hallmark Movies & Mysteries HD",
  "Reelz Channel HD",
  "Tru TV HD",
  "Revolt HD",
  "Fusion HD",
  "Fuse HD",
  "GSN HD",
  "POP HD",
  "CMT HD",
  "FYI HD",
  "TLC HD",
  "PBS HD",
  "BET HD",
  "IFC HD",
  "LMN HD",
  "MTV2 HD",
  "VH1 HD",
  "WE TV HD",
  "Viceland HD",
  "AXS TV HD",
  "TVLand HD",
  "TVOne HD",
  "Daystar HD",
  "CBN HD",
  "SBN HD",
  "TBN HD",
  "Fight Tyme",
  "QVC HD",
  "Impact Network",
  "Bloomberg HD",
  "ABC Atlanta HD",
  "ABC Boston HD",
  "ABC Chicago HD",
  "ABC Dallas HD",
  "ABC Houston HD",
  "ABC Los Angeles HD",
  "ABC Miami HD",
  "ABC New York HD",
  "CBS Atlanta HD",
  "CBS Boston HD",
  "CBS Chicago HD",
  "CBS Detriot HD",
  "CBS Houston HD",
  "CBS Los Angeles HD",
  "CBS Miami HD",
  "CBS New York HD",
  "CBS Phoenix HD",
  "FOX Atlanta HD",
  "FOX Chicago HD",
  "FOX Dallas HD",
  "FOX Houston HD",
  "FOX Los Angeles HD",
  "FOX Miami HD",
  "FOX New York HD",
  "NBC Boston HD",
  "NBC Chicago HD",
  "NBC Dallas HD",
  "NBC Houston HD",
  "NBC Los Angeles HD",
  "NBC Miami HD",
  "NBC New York HD",
  "NBC Philadelphia HD",
  "HLN HD",
  "Peace TV HD",
  "MBC 1 HD",
  "MBC 2 HD",
  "MBC 3 HD",
  "MBC 4 HD",
  "MBC Action HD",
  "MBC Bollywood",
  "MBC Drama HD",
  "MBC Maser",
  "MBC Max HD",
  "ART Aflam 1",
  "ART Aflam 2",
  "ART Cinema",
  "ART Hekayat 1",
  "ART Hekayat 2",
  "Iqraa TV",
  "Nogoum FM TV",
  "OSN Cinema 1",
  "OSN FX HD",
  "OSN Mousalsalat",
  "OSN Movies Kids",
  "OSN MusalSat",
  "OSN Music Now",
  "OSN Series First",
  "OSN Star Movies HD",
  "OSN Star World HD",
  "OSN Ya Hala Al Oula",
  "OSN Ya Hala Cinema",
  "OSN Ya Hala HD",
  "OSN Ya Hala Shabab",
  "Rotana Cinema",
  "Rotana Classic",
  "Rotana Clip",
  "Rotana Khalijiah",
  "Rotana Masriya",
  "Rotana Music",
  "SeeVii Beelink HD",
  "SeeVii Drama HD",
  "SeeVii Shamiya HD",
  "Seevii Al ola HD",
  "Sunna TV",
  "Al Hadath",
  "Nile Cinema",
  "Nile Comedy",
  "Nile Culture",
  "Nile Drama",
  "Nile Family",
  "Nile Life",
  "Nile News",
  "CBC",
  "CBC Drama",
  "CBC Extra",
  "CBC Sofra",
  "Sama Syria TV",
  "Syria TV",
  "Al Jazeera",
  "Al Jazeera Doc",
  "Al Jazeera English",
  "Al Jazeera Mubasher",
  "Al Magharibia",
  "Al Magharibia 2",
  "SNTV",
  "Universal TV",
  "SLN TV",
  "Kalsan TV",
  "Horn Cable TV",
  "Jubbaland TV",
  "SBC TV",
  "Star TV",
  "Somali Cable TV",
  "Somali TV4",
  "Bulsho TV",
  "Puutland TV",
  "ESTV",
  "BeIN Sports News AR HD",
  "BeIN Sports 1 AR HD",
  "BeIN Sports 2 AR HD",
  "BeIN Sports 3 AR HD",
  "BeIN Sports 4 AR HD",
  "BeIN Sports 5 AR HD",
  "BeIN Sports 6 AR HD",
  "BeIN Sports 7 AR HD",
  "BeIN Sports 8 AR HD",
  "BeIN Sports 9 AR HD",
  "BeIN Sports 10 AR HD",
  "MBC Pro Sports 1 HD",
  "MBC Pro Sports 2 HD",
  "MBC Pro Sports 3 HD",
  "OSN Sports 1",
  "OSN Sports 2",
  "OSN Sports 3",
  "OSN Sports 4",
  "LBC",
  "LDC",
  "Al Jadeed",
  "Al Manar",
  "Al Mayadeen",
  "Future TV",
  "NBN",
  "BeIN Movies 1 HD",
  "BeIN Movies 2 HD",
  "BeIN Movies 3 HD",
  "TF1 HD",
  "France 2 HD",
  "France 3 HD",
  "France 4 HD",
  "France 5 HD",
  "M6 HD",
  "Arte HD",
  "C8 HD",
  "TMC HD",
  "NT1 HD",
  "NRJ 12 HD",
  "BFM TV HD",
  "iTele HD",
  "HD1",
  "C Star HD",
  "6Ter HD",
  "Numero 23 HD",
  "RMC Decouverte HD",
  "Canal + HD",
  "Canal+ Cinema HD",
  "Canal+ Family HD",
  "Canal+ Decale HD",
  "Canal+ Series HD",
  "Cine+ Premier HD",
  "Cine+ Frisson HD",
  "Cine+ Famiz HD",
  "Cine+ Emotion HD",
  "Cine+ Club HD",
  "Cine+ Classic HD",
  "Cine Polar HD",
  "Cine FX HD",
  "Paramount Channel HD",
  "TCM Cinema HD",
  "OCS City HD",
  "OCS Choc HD",
  "OCS Max HD",
  "OCS Geants HD",
  "Comedie+ HD",
  "13EME Rue HD",
  "RTL9 HD",
  "Serie Club HD",
  "Planete+ HD",
  "Planete+ A&E HD",
  "Planete+ CI HD",
  "Discovery Channel FR HD",
  "Discovery Science FR HD",
  "Discovery Investigation FR HD",
  "Nat Geo FR HD",
  "Nat Geo Wild FR HD",
  "Histoire HD",
  "Animaux HD",
  "Disney Channel FR HD",
  "Disney Cinema HD",
  "Disney Junior FR HD",
  "Disney XD FR HD",
  "Nickelodeon FR HD",
  "Teletoon+ FR HD",
  "Boing HD",
  "Boomerang FR HD",
  "Cartoon Network FR HD",
  "InfoSport+ HD",
  "L'Equipe HD",
  "Canal+ Sport HD",
  "BeIN Sports 1 FR HD",
  "BeIN Sports 2 FR HD",
  "BeIN Sports 3 FR HD",
  "Channel #1",
  "Channel #2",
  "Channel #3",
  "Channel #4",
  "Channel #5",
  "Channel #6",
  "Channel #7",
  "Channel #8",
  "Channel #9",
  "Channel #10",
  "Channel #11",
  "Channel #12",
  "Channel #13",
  "Channel #14",
  "Channel #15",
  "Channel #16",
  "Channel #17",
  "Channel #18",
  "Channel #19",
  "Channel #20",
  "Channel #21",
  "Channel #22",
  "Channel #23",
  "Channel #24",
  "Channel #25",
  "Channel #26",
  "Channel #27",
  "Channel #28",
  "Channel #29",
  "Channel #30",
  "Channel #31",
  "Channel #32",
  "Channel #33",
  "Channel #34",
  "Channel #35",
  "Channel #36",
  "Channel #37",
  "Channel #38",
  "Channel #39",
  "Channel #40",
  "Channel #41",
  "Channel #42",
  "Channel #43",
  "Channel #44",
  "Channel #45",
  "Channel #46",
  "Channel #47",
  "Channel #48",
  "Channel #49",
  "Channel #50",
  "Channel #51",
  "Channel #52",
  "Channel #53",
  "Channel #54",
  "Channel #55",
  "Channel #56",
  "Channel #57",
  "Channel #58",
  "Channel #59",
  "Channel #60",
  "Channel #61",
  "Channel #62",
  "Channel #63",
  "Channel #64",
  "Channel #65",
  "Channel #66",
  "Channel #67",
  "Channel #68",
  "Channel #69",
  "Channel #70",
  "Channel #71",
  "Channel #72",
  "Channel #73",
  "Channel #74",
  "Channel #75",
  "Channel #76",
  "Channel #77",
  "Channel #78",
  "Channel #79",
  "Channel #80",
  "Channel #81",
  "Channel #82",
  "Channel #83",
  "Channel #84",
  "Channel #85",
  "Channel #86",
  "Channel #87",
  "Channel #88",
  "Channel #89",
  "Channel #90",
  "Channel #91",
  "Channel #92",
  "Channel #93",
  "Channel #94",
  "Channel #95",
  "Channel #96",
  "Channel #97",
  "Channel #98",
  "Channel #99",
  "Channel #100",
  "Channel #101",
  "Channel #102",
  "Channel #103",
  "Channel #104",
  "Channel #105",
  "Channel #106",
  "Channel #107",
  "Channel #108",
  "Channel #109",
  "Channel #110",
  "Channel #111",
  "Channel #112",
  "Channel #113",
  "Channel #114",
  "Channel #115",
  "Channel #116",
  "Channel #117",
  "Channel #118",
  "Channel #119",
  "Channel #120",
  "Channel #121",
  "Channel #122",
  "Channel #123",
  "Channel #124",
  "Channel #125",
  "Channel #126",
  "Channel #127",
  "Channel #128",
  "Channel #129",
  "Channel #130",
  "Channel #131",
  "Channel #132",
  "Channel #133",
  "Channel #134",
  "Channel #135",
  "Channel #136",
  "Channel #137",
  "Channel #138",
  "Channel #139",
  "Channel #141",
  "Channel #140",
  "Channel #142",
  "Channel #143",
  "Channel #144",
  "Channel #145",
  "Channel #146",
  "Channel #147",
  "Channel #148",
  "Channel #149",
  "Channel #150",
  "Channel #300",
  "Rangers TV HD",
  "MLB #1",
  "MLB #2",
  "MLB #3",
  "MLB #4",
  "MLB #5",
  "MLB #6",
  "MLB #7",
  "MLB #8",
  "MLB #9",
  "MLB #10",
  "MLB #11",
  "MLB #12",
  "MLB #13",
  "NHL #1",
  "NHL #2",
  "NHL #3",
  "NHL #4",
  "NHL #5",
  "NHL #6",
  "NHL #7",
  "NHL #8",
  "NHL #9",
  "NHL #10",
  "NHL #11",
  "NHL #12",
  "NHL #13",
  "NHL #14",
  "NHL #15",
  "NFL #1",
  "NFL #2",
  "NFL #3",
  "NFL #4",
  "NFL #5",
  "NFL #6",
  "NFL #7",
  "NFL #8",
  "NFL #9",
  "NFL #10",
  "NFL #11",
  "NFL #12",
  "NFL #13",
  "NFL #14",
  "NFL #15",
  "NFL #16",
  "NBA #1",
  "NBA #2",
  "NBA #3",
  "NBA #4",
  "NBA #5",
  "NBA #6",
  "NBA #7",
  "NBA #8",
  "NBA #9",
  "NBA #10",
  "Le Sports Now 1 HD",
  "Le Sports Now 2 HD",
  "Le Sports Now 3 HD",
  "Le Sports Now 4 HD",
  "Le Sports Now 5 HD",
  "Le Sports Now 6 HD",
  "Le Sports Now 7 HD",
  "Le Sports Now Premier League TV HD",
  "NBC Gold One HD",
  "NBC Gold Two HD",
  "NBC Gold Three HD",
  "NBC Gold Four HD",
  "NBC Gold Five HD",
  "NBC Gold Rush TV HD",
  "BT Sports Extra 1",
  "BT Sports Extra 2",
  "BT Sports Extra 3",
  "BT Sports Extra 4",
  "BT Sports Extra 5",
  "BT Sports Extra 6",
  "Cinemax",
  "Cinemax 5 Star",
  "Cinemax Actionmax",
  "Cinemax Moremax",
  "HBO",
  "HBO2 HD",
  "HBO Family HD",
  "HBO Comedy HD",
  "HBO Signature HD",
  "HBO Zone HD",
  "HBO East CA HD",
  "HBO West CA HD",
  "Starz HD",
  "Starz Kids & Family",
  "Starz Encore",
  "Starz Edge",
  "Starz Comedy",
  "Showtime HD",
  "Showtime 2 HD",
  "Showtime Extreme HD",
  "Epix HD",
  "Epix 2 HD",
  "Epix Hits HD",
  "Super Channel 1 HD",
  "Super Channel 3 HD",
  "Super Channel 4 HD",
  "Sky Cinema Select HD",
  "Sky Cinema Family HD",
  "Sky Cinema Disney HD",
  "Sky Cinema Heroes HD",
  "Sky Cinema Hits HD",
  "The Movie Channel HD",
  "HDNet Movies HD",
  "Captain News",
  "Captain TV",
  "Jaya Movies US",
  "Jaya TV US",
  "KTV",
  "KTV US",
  "Raj Digital Plus",
  "Raj News",
  "Raj TV",
  "Raj TV US",
  "SUN TV",
  "SUN TV US",
  "Star Vijay",
  "9x Tashan",
  "Alpha ETC Punjabi",
  "PTC Chak De",
  "PTC News",
  "PTC Punjabi",
  "Prime Asia",
  "MH1 News",
  "Gaunda Punjab TV",
  "Garv Punjabi TV",
  "DD Punjabi",
  "Desi Channel",
  "Chardikla Time TV",
  "Zee Punjabi",
  "Sikh Channel",
  "92 News HD",
  "A Entertainment",
  "A Plus",
  "ARY Digital",
  "ARY Zindagi",
  "ATV Entertainment",
  "AXN Pakistan",
  "Aaj News",
  "Abbtakk",
  "Al-Rehman Al-Rahim",
  "Ary Digital USA",
  "Ary News",
  "Ary News USA",
  "Ary QTV",
  "Bol TV HD",
  "Business Plus",
  "Cartoon Network Pakistan",
  "Channel 24 HD",
  "Dawn News",
  "Dunya News",
  "Express Entertainment",
  "Express News",
  "Geo Entertainment",
  "Geo Kahani",
  "Geo News",
  "Geo Super",
  "Geo USA",
  "Hadi TV",
  "Hum Masala TV",
  "Hum Sitary",
  "Hum TV",
  "Hum World",
  "KTN Entertainment",
  "KTN News",
  "Kashish",
  "Khyber News",
  "MTA Urdu",
  "Metro 1",
  "News One",
  "PTV Global",
  "PTV Home",
  "PTV News",
  "PTV World",
  "Pak News HD",
  "Pashtoo 1",
  "Samma News",
  "Sindh News",
  "Sindh TV",
  "Such News",
  "TV One",
  "Toonami",
  "Urdu 1",
  "Waqt News",
  "Zaiqa",
  "Health TV",
  "&Pictures HD",
  "Aajtak",
  "Aastha Bhajan",
  "Aastha TV",
  "B4U Movies",
  "Colors India HD",
  "Discovery Kids India",
  "Star Bharat India HD",
  "Star Bharat USA",
  "MTV India",
  "NDTV India",
  "Nick Jr India",
  "Nick Sonic India",
  "Nickelodeon India HD",
  "Sanskar TV",
  "Sony ESPN HD",
  "Sony Max India HD",
  "Sony Mix",
  "Sony Pal",
  "Sony TV India HD",
  "Sony TV USA HD",
  "Sony Le Plex HD",
  "Sony Rox HD",
  "Sony SAB HD",
  "Star Gold India HD",
  "Star Gold Select HD",
  "Star Gold Select HD US",
  "Star Plus India HD",
  "Star Plus USA",
  "Star Sports 1 HD",
  "Star Sports 1 Select HD",
  "Star Sports 2 HD",
  "Star Sports 2 Select HD",
  "Star World HD",
  "Star World Premier HD",
  "TLC India",
  "Travel XP India HD",
  "UTV Action",
  "UTV Movies",
  "D2H Cinema HD",
  "D2H Classics HD",
  "D2H Kids Rhymes HD",
  "D2H Movies HD",
  "Zee Cinema",
  "Zee Cinema India HD",
  "Zee Classic",
  "Zee TV HD USA",
  "Zee TV India HD",
  "Star Plus UK",
  "&TV HD",
  "Sony Mix UK",
  "Sony Set Max UK",
  "Star Gold UK",
  "Rishtey Cineplex UK",
  "Rishtey TV",
  "Sony Max UK",
  "ATN Afghan",
  "ATN News",
  "ATN USA",
  "ATV AFG",
  "Aria Music",
  "Ariana",
  "Shamshad",
  "Tolo News",
  "Tolo TV",
  "Akash Bangla",
  "Boishakhi TV",
  "Channel 9 HD",
  "Channel Eye Europe",
  "Channel I",
  "Colors Bangla",
  "Dhoom Music",
  "Ekattor TV",
  "Gaan Bangla",
  "Jalsha Movies",
  "Jamuna TV",
  "Masranga TV",
  "Mohona TV",
  "Movie Bangla",
  "Star Jalsha",
  "Star Jalsha Movies",
  "Zee Bangla",
  "IBN 7 News",
  "Colors Marathi",
  "MR 24 Taas",
  "MR Zee HD",
  "MR Saam TV",
  "MR Jai Maharashtra",
  "MR Star Pravah",
  "MR TV9",
  "MR Zee Talkies",
  "MR IBN Lokmat",
  "Amrita TV",
  "Asianet TV",
  "Asianet Plus",
  "Asianet News",
  "Asianet Movies",
  "Flowers TV",
  "Jai Hind",
  "DD Malayalam",
  "Kairali TV",
  "Janam TV",
  "Jeevan TV",
  "Kerala Vision",
  "Kiran TV",
  "Mazhavil Manorama",
  "Marian TV",
  "Manorama News",
  "Mathrubhoomi",
  "CNBC Bazaar",
  "Colors Gujrati",
  "ETV News",
]

module.exports = channels;